server:
  port: 10000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangxiuzhi/configrepo.git
          basedir: /Users/zhangxiuzhi/repo
  application:
    name: Config-Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
