server:
  port: 9003
spring:
  datasource:
    url: jdbc:mysql://rm-bp1091w7xps7t6rmz.mysql.rds.aliyuncs.com/tps?useUnicode=true&characterEncoding=utf8
    username: '{cipher}AQBIhwbT2Dooiwo9WCqxAmpUmCEq2fxsP7V+6EkHoq6hevgYbx7fqukgL5AlcnrQB22StaBCbXwey/WqSmrotQcC54AurG7NnAeFHtSk0q5CD8bsG2bxaHoVzKtri1iq36rXPv/hBwnVBcOyRiPys43xHkqwfqeze6+cnlqUfZiV9dMixyxO60c6dFaOwGKZ2eWfKdaFsyw7lxHq9RAuC7lG9rVxI/kZVF9CkO024tpfL9NEbXeYatU/jVGsI8T+uohJq4JlUbYwlDEvU+C0U0hAU4z534R7lS3NqwYU49fC8hZHoNmq4C/fH11Nh7c3Yy0NzQbGCTihE4fGsTkjP0YtQcG6jarRuuLtKMlGroxPk2wfVqqgiF7TnEGFtYXS3vI='
    password: '{cipher}AQAZfBCLXDoB5+CvB911JWIXkrtek0drnlfslT6AS7+4x0W5zYwIsUdvuUvtLI4rqzeV4PyD5+k6y8KzoNLQtlSO6iCgamFCIFIgW0cF55f3FiCO7oST2jwT8ujcpxuXqCnzOs/rootoccwe/49z9ACgL37rTmPq25qr0IekicPbVbQ6VaxBBGJNx9MnuHwauW4SD/CvgSjYZp3SGoeOmDHhv0gm4Gkr6DkeQ7WSa4mxA4YIETq733cYigPfIbQdluXmBaGvX/PVpWU7mhiaFqaaLnRvlw91MkhM2tbDcfZJW/lDtHKe/2qtV7siSNSjgtS+mobJ9nhUKGEIX1wBL3z9EKMta5DW67NxtBLMWv8wJAQYrhCALxi/1iVVkzUvZRM='
    druid:
      max-active: 5
      max-wait: 20000
      min-idle: 1
      filters: stat,wall
#  redis:
#    host: 172.18.1.120
#  cache:
#    type: redis
#    cache-names: platinfo,session,base,account,user,user_pic
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        ddl-auto: none
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML
  session:
    store-type: hash_map
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  devtools:
    restart:
      trigger-file: IndexController.class
logging:
  level:
   org:
    hibernate:
      type:
        descriptor:
          sql:
            BasicBinder: trace
#    springframework:
#      security: debug
debug: true
