server:
  port: 9003
spring:
  datasource:
    url: jdbc:mysql://rm-bp1091w7xps7t6rmz.mysql.rds.aliyuncs.com/tps?useUnicode=true&characterEncoding=utf8
    username: '{cipher}AQAP1tYPiOR3IKzhlEOa2cJ6M3paf8CdnxKrAF4fe1SQ7gOeQKZpWCXqrhRgHuguavH4OucsFJ3t3tmyug1HlPgvmgQn5iV0a9fFpxraWOR8e7TRHgKaQuNC3qh70WGJ4S8uluXPJ6F5YsQp0qVffkixUxRP7lEVXMXJodSJDT2CIh96q0j9miBgQPAsEzhelNe73DdIafYZbvKRde4wV2H29V+F2/NQTCRZnRQ77NCJxVktbKdz87C+RwRMuxE2b5XXcY9vcPU1CwvB41+JCgI2HNzIKoJGbRRCxYlKWbDhBmKSLRpau8NEfQS0+Re90+8gMtNjggoH/b4VeItqhRo8a09NaEqtsVnOMTtyFyvRvP6DmI4LuK4uPrDUi3eUAJA='
    password: '{cipher}AQA31eRVEcXcp57xmsZ/7CmHlJubG+v3KFsJi0GA5IMHJmxHP30fJVwY3KeRStRY20WtcsSadOGaL8xQvTaQJrYv0RtGT1CTJedyvnO68IzQavnPX7HYZgLVTHdoOR/fL5SA4CNtui7Hes6ofLpR4EXxx/DNkJHrnv6073+ZLVL3oAyLE54dBXhr32qdt7RJWcF6wb20oSg1gAkUs11iLm1xE+FvAkGKpWDr1CwBSBGloqoz3q6/+CN7WpMxaZNUCyIfCLi9dmcQ+dXo/hZUNUg2TbAasXs2zZKZaV1HOaJ+KjhStgkSxWKdDxvXSuK3i4eDja/kt0KxImbTsoSqKRHcdbsKhWVDWsxpuNmCr+FmE7baqVdyOGgnW86Pw8BRbnA='
    druid:
      max-active: 5
      max-wait: 20000
      min-idle: 1
      filters: stat,wall
#  redis:
#    host: 172.18.1.120
#  cache:
#    type: redis
#    cache-names: platinfo,session,base,account,user,user_pic
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        ddl-auto: none
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML
  session:
    store-type: hash_map
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  devtools:
    restart:
      trigger-file: IndexController.class
logging:
  level:
   org:
    hibernate:
      type:
        descriptor:
          sql:
            BasicBinder: trace
#    springframework:
#      security: debug
debug: true
